### ISSUE TITLE
The mixing of differing integer types makes the search algorithms defective

### ISSUE THREAD

**Issue by mclow** [mclow/Boost.Algorithm#15]
Neil Groves wrote:
The mixing of differing integer types makes the search algorithms defective.
The int type is signed, and typically <= the size of std::size_t yet these
are mixed. The skip table uses ints, but std::size_t values are inserted.
Certainly there should not be any c style casts. It would seem logical to
use the boost::iterator_difference<Iterator>::type instead. Currently these
algorithms are defective albeit under unusual conditions.

There are numerous invocations of non-member functions that should use
qualified calls to avoid accidental argument-dependent lookup.

range_const_iterator<Rng> has been deprecated in favour of
range_iterator<const Rng>

The Range versions of the functions should provide a non-const reference
version since there are no requirements for the interoperability of
range_iterator<const Range> and range_iterator<Range> although they normally
exist..

**Comment by dabrahams** [comment]
It would be good to have tests implemented that demonstrate these defects before they are fixed.

**Comment by mclow** [comment]
I have pushed new versions of the search algorithms; I think I've resolved all the signed/unsigned comparisons, as well as removing all the c-style (I think).

**Comment by dabrahams** [comment]
What about the tests?

BTW, if you put "fixes #15" or "closes #15" in your commit comment we'd all be able to click on a link here and see the changes you made.

**Comment by mclow** [comment]
I didn't put that there because it's not completely fixed.
The ADL concerns have not been addressed, as well as the range types.

And, as you said, tests.

**Comment by dabrahams** [comment]
Oh, thanks. Well then refs or references #15 probably would work
